/**
 * This code was generated by Diez version 10.6.0.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */
import { Color, File, Font, Image, Typograph } from "@diez/prefabs";

const diezDemoColors = {
    textDarkGray: Color.rgba(66, 66, 66, 1),
    secondary: Color.rgba(45, 156, 219, 1),
    textDark: Color.rgba(36, 36, 36, 1),
    primary: Color.rgba(235, 87, 87, 1),
    textGray: Color.rgba(130, 130, 130, 1)
};

const diezDemoTypography = {
    description: new Typograph({ letterSpacing: 0, fontSize: 14, lineHeight: 16.40625, color: Color.rgba(66, 66, 66, 1), font: new Font({ name: "OpenSans-Regular" }) }),
    link: new Typograph({ letterSpacing: 0, fontSize: 12, lineHeight: 14.0625, color: Color.rgba(45, 156, 219, 1), font: new Font({ name: "OpenSans-SemiBold" }) }),
    title: new Typograph({ letterSpacing: 0, fontSize: 18, lineHeight: 24, color: Color.rgba(36, 36, 36, 1), font: new Font({ name: "OpenSans-Bold" }) })
};

export const diezDemoImagesFiles = {
    logoLight: new File({ src: "assets/DiezDemo.figma.contents/images/LogoLight.png" }),
    logoLight2x: new File({ src: "assets/DiezDemo.figma.contents/images/LogoLight@2x.png" }),
    logoLight3x: new File({ src: "assets/DiezDemo.figma.contents/images/LogoLight@3x.png" }),
    logoLight4x: new File({ src: "assets/DiezDemo.figma.contents/images/LogoLight@4x.png" }),
    logoMono: new File({ src: "assets/DiezDemo.figma.contents/images/LogoMono.png" }),
    logoMono2x: new File({ src: "assets/DiezDemo.figma.contents/images/LogoMono@2x.png" }),
    logoMono3x: new File({ src: "assets/DiezDemo.figma.contents/images/LogoMono@3x.png" }),
    logoMono4x: new File({ src: "assets/DiezDemo.figma.contents/images/LogoMono@4x.png" })
};

/**
 * This is provided for backward compatibility, please use `diezDemoImagesFiles` instead.
 * @deprecated
 */
export const diezDemoComponentsFiles = diezDemoImagesFiles;

export const diezDemoImages = {
    logoLight: Image.responsive("assets/DiezDemo.figma.contents/images/LogoLight.png", 80.78738403320312, 110),
    logoMono: Image.responsive("assets/DiezDemo.figma.contents/images/LogoMono.png", 80.78738403320312, 110)
};

/**
 * This is provided for backward compatibility, please use `diezDemoImages` instead.
 * @deprecated
 */
export const diezDemoComponents = diezDemoImages;

export const diezDemoTokens = {
    colors: diezDemoColors,
    typography: diezDemoTypography
};
